apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nodejs-qbfcpqaz 
  janus-idp.io/tekton: nodejs-qbfcpqaz
  backstage.io/kubernetes-id: nodejs-qbfcpqaz
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nodejs-qbfcpqaz
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml